# docker/docker-compose.yml
version: "3.9"

services:
  db:
    image: postgres:15
    container_name: betmanager_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: betmanager
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: betmanager_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: betmanager_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

volumes:
  db_data: